version: '3'

services:
  1inch-monitor:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: CHANGEME
      TELEGRAM_CHAT_ID:  CHANGEME
      RULES: |-
        1 USDC-ETH-USDC >= 1 !0X Relays
        1 DAI-ETH-DAI >= 1