version: '3'

services:
  1inch-monitor:
    build: .
    environment:
      TELEGRAM_BOT_TOKEN: CHANGEME
      TELEGRAM_CHAT_ID:  CHANGEME
      RULES: |-
        1 USDC >= 1.01 DAI !0X Relays
        1 DAI >= 1.01 USDC !OX Relays,Uniswap,Kyber
        1 ETH >= 250 USDC !AirSwap,Kyber,Uniswap
        250 DAI <= 1 ETH